### ISSUE TITLE
Support more ways to control docker images other than environment variables

### ISSUE THREAD

**Issue by eladav** [Soluto/dynamico#58]
currently you control docker deployments with setting environment variables which is an easy solution but considered not secure. These environment variables contain connection strings and maybe other sensitive information. We should allow configuration via files and any other way that makes sense for running dynamico in a container.

**Comment by mikeChatsky** [comment]
How about offering the option to add docker configuration secrets stored in files as the docker docs suggest:
https://docs.docker.com/compose/compose-file/#secrets-configuration-reference - with compose.
https://docs.docker.com/engine/swarm/secrets/ - with docker secrets.

That way, both options (environment variables and secret files) can be available to choose from. Or perhaps the container can use secrets files alone in order to standardize security best-practices.

I wouldn't mind taking a shot at implementing it if this approach seems acceptable :)

**Comment by eladav** [comment]
Hey Mike, thanks for the response 😃
Sounds like a good approach, I think it would also make us more conformant with other tools in the ecosystem (e.g. k82 secret managers).... a PR would be very appreciated :)
